spring:
  application:
    name: incluses-api-redis

    redis:
      host: virginia-redis.render.com
      port: 6379
      password: Gx2DMU1DMXqDfaYpZFg4TW8lDcYCDcJZ
      ssl: true # Usar SSL para 'rediss://'

    cache:
      type: redis